server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msvc_usuarios?serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=false
    username: root
    password: developer2021
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

  application:
    name: msvc-usuarios

logging:
  level:
    org:
      hibernate:
        SQL: debug